### ISSUE TITLE
Tuple size?

### ISSUE THREAD

**Issue by KenanSulayman** [aatxe/markov#12]
Hey,

I'm working on a fitting a model to user behaviour data and was wondering how the data is structured inside this library. Specifically, I wonder how you deal with n-tuples: if you have a state s1, s2, s3 and s4, how is the chain s1 -> s4 stored?

I found multiple naive implementations (not this) that were actually just tuples: s1 -> s2, s2 -> s3, which isn't exactly accurate. Maybe you could outline the architecture of this library in a few words in the readme?

Thanks 🍻

**Comment by aatxe** [comment]
It's been a long while since you posted this, but the gist is that it keeps rolling windows of order-`n` tokens that map to the next token. So, for string tokens, something like "foo bar baz bop" at order 2 becomes `() -> foo`, `(foo) -> bar`, `(foo bar) -> baz`, `(bar baz) -> bop`, and `(baz bop) -> ⊥`.
